version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  graphql-engine:
    image: hasura/graphql-engine:v2.0.10
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  frontend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - 'graphql-engine'
    environment:
      VITE_APP_GRAPHQL_HTTP: http://localhost:8080/v1/graphql

volumes:
  db_data: